{{- $global := .Values }}
{{- range $cluster := .Values.pgClusters.clusters }}
{{- with $global }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    {{ include "labels.common" $ | nindent 4 }}
  name: {{ $cluster.name }}
  namespace: {{ $cluster.namespace }}
spec:
  jobTemplate:
    metadata:
      labels:
        {{ include "labels.common" $ | nindent 8 }}
    spec:
      backoffLimit: {{ $global.cronjob.backoffLimit }}
      template:
        metadata:
          labels:
            {{ include "labels.common" $ | nindent 12 }}
        spec:
          containers:
          - command:
            - ./etc/config/test-script.sh
            image: "{{ $global.registry }}/{{ $global.cronjob.image.name }}:{{ $global.cronjob.image.tag }}"
            imagePullPolicy: IfNotPresent"
            name: {{ $global.cronjob.name }}
            env:
            - name: TEST_TIMEOUT
              value: {{ $cluster.testTimeout }}
            resources:
              {{- toYaml $global.cronjob.resources | nindent 14 }}
            securityContext:
              {{- toYaml $global.cronjob.containerSecurityContext | nindent 14 }}
            volumeMounts:
            - name: pg-cluster-recovery-template
              mountPath: /etc/config
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          securityContext:
            {{- toYaml $global.cronjob.podSecurityContext | nindent 12 }}
          serviceAccountName: {{ $global.cronjob.serviceAccount.name }}
          volumes:
          - name: pg-cluster-recovery-template
            configMap:
              name: {{ $cluster.name }}
  terminationGracePeriodSeconds: 30
  schedule: {{ $cluster.schedule }}
{{- end }}
{{- end }}
