apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ .Values.pgCluster.name }}
  namespace: {{ .Values.pgCluster.namespace }}
spec:
  jobTemplate:
    metadata:
      labels:
        {{- include "labels.common" . | nindent 8 }}
    spec:
      backoffLimit: {{ .Values.cronjob.backoffLimit }}
      template:
        metadata:
          labels:
            {{- include "labels.common" . | nindent 12 }}
        spec:
          containers:
          - command:
            - /etc/config/test-script.sh
            image: "{{ .Values.global.registry }}/{{ .Values.cronjob.image.name }}:{{ .Values.cronjob.image.tag }}"
            imagePullPolicy: {{ .Values.cronjob.image.pullPolicy }}
            name: "pg-cluster-recovery-test"
            env:
            - name: TEST_TIMEOUT
              value: "{{ .Values.cronjob.testTimeout }}"
            - name: WAIT_TIMEOUT
              value: "{{ .Values.cronjob.waitTimeout }}"
            resources:
              {{- toYaml .Values.cronjob.resources | nindent 14 }}
            securityContext:
              {{- toYaml .Values.cronjob.containerSecurityContext | nindent 14 }}
            volumeMounts:
            - name: pg-cluster-recovery-template
              mountPath: /etc/config
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          securityContext:
            {{- toYaml .Values.cronjob.podSecurityContext | nindent 12 }}
          serviceAccountName: {{ .Values.cronjob.serviceAccount.name }}
          volumes:
          - name: pg-cluster-recovery-template
            configMap:
              name: {{ .Values.pgCluster.name }}
              defaultMode: {{ .Values.cronjob.configMap.defaultMode }}
  terminationGracePeriodSeconds: 30
  schedule: {{ .Values.cronjob.schedule }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
