apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    {{ include "labels.common" . | nindent 4 }}
  name: {{ .Values.cronjob.name }}
  namespace: {{ .Values.cronjob.namespace }}
spec:
  jobTemplate:
    metadata:
      labels:
        {{ include "labels.common" . | nindent 8 }}
    spec:
      backoffLimit: {{ .Values.cronjob.backoffLimit }}
      template:
        metadata:
          labels:
            {{ include "labels.common" . | nindent 12 }}
        spec:
          containers:
          - command:
            - TODO
            image: "{{ .Values.registry }}/{{ .Values.cronjob.image.name }}:{{ .Values.cronjob.image.tag }}"
            imagePullPolicy: IfNotPresent"
            name: {{ .Values.cronjob.name }}
            resources:
              {{- toYaml .Values.cronjob.resources | nindent 14 }}
            securityContext:
              {{- toYaml .Values.cronjob.containerSecurityContext | nindent 14 }}
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext:
            {{- toYaml .Values.cronjob.podSecurityContext | nindent 12 }}
          serviceAccountName: {{ .Values.cronjob.serviceAccount.name }}
  terminationGracePeriodSeconds: 30
  schedule: {{ .Values.cronjob.schedule }}
