apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.pgCluster.name }}
  namespace: {{ .Values.pgCluster.namespace }}
data:
  {{- $files := .Files }}
  {{- range tuple "files/pg-recovery-cluster.yaml" "files/test-script.sh" }}
  {{ . | base }}: |
    {{- tpl ($files.Get .) $ | nindent 4 -}}
  {{- end }}
