{{- $global := .Values }}
{{- range $cluster := .Values.pgClusters.clusters }}
{{- with $global }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $cluster.name }}
  namespace: {{ $cluster.namespace }}
data:
  # file-like keys
  pg-recovery-cluster.yaml: |
    apiVersion: postgresql.cnpg.io/v1
    kind: Cluster
    metadata:
      labels:
        {{ include "labels.common" . | nindent 4 }}
      name: {{ $cluster.name }}
      namespace: {{ $cluster.namespace }}
    spec:
      instances: {{ $cluster.instances }}
      imageName: {{ $global.registry }}/{{ $global.pgClusters.image.name }}:{{ $global.pgClusters.image.tag }}
      postgresql:
        parameters:
          # Maximum size of the WAL
          max_wal_size: '512MB'
          # Specifies the minimum size of past WAL files kept in the pg_wal directory
          wal_keep_size: '128MB'
          # Specify the maximum size of WAL files that replication slot
          max_slot_wal_keep_size: '128MB'
      storage:
        size: {{ $cluster.storageSize }}
      bootstrap:
        recovery:
          source: {{ $cluster.backupCluster.name }}
      externalClusters:
      - name: {{ $cluster.backupCluster.name }}
        barmanObjectStore:
          {{- if (eq $global.provider "capa") }}
          destinationPath: {{ $cluster.backupCluster.destinationPath }}
          s3Credentials:
            inheritFromIAMRole: true
          {{- end }}
          {{- if or (eq $global.provider "capz") (and (eq .customer "giantswarm") (or (eq $global.provider "vsphere") (eq $global.provider "cloud-director"))) }}
          destinationPath: {{ $cluster.backupCluster.destinationPath }}
          azureCredentials:
            storageAccount:
              name: {{ $cluster.backupCluster.azureSecret.secretName }}
              key: {{ $cluster.backupCluster.azureSecret.name }}
            storageKey:
              name: {{ $cluster.backupCluster.azureSecret.name }}
              key: {{ $cluster.backupCluster.azureSecret.key }}
          {{- end }}
          wal:
            maxParallel: 8
      {{- end }}
      {{- if (eq $global.provider "capa") }}
      serviceAccountTemplate:
        metadata:
          annotations:
            {{ toYaml $cluster.serviceAccount.annotations | nindent 8}}
      {{- end }}
{{- end }}
{{- end }}
