{{- if .Values.cronjob.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ .Values.cronjob.serviceAccount.name }}
  namespace: {{ .Values.cronjob.namespace }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
  {{- include "labels.common" . | nindent 4 }}
  name: {{ template "pg-cluster-recovery-test.name" . }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - watch
  - list
  - delete
- apiGroups:
  - postgresql.cnpg.io
  resources:
  - clusters
  verbs:
  - get
  - watch
  - list
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
  {{- include "labels.common" . | nindent 4 }} 
  name: {{ template "pg-cluster-recovery-test.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "pg-cluster-recovery-test.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.cronjob.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
