global:
  registry: gsoci.azurecr.io
  provider: capa
  customer: ""

cronjob:
  image:
    name: giantswarm/kubectl
    tag: 1.31.1
  
  schedule: "0 10 * * *" # Every day at 10:00 UTC
  testTimeout: 1800 # 30 minutes
  
  backoffLimit: 3

  serviceAccount:
    create: true
    name: pg-cluster-recovery-test

  resources: {}

  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    privileged: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  podSecurityContext:
    fsGroup: 1000
    runAsUser: 1000

pgCluster:
  image:
    name: giantswarm/postgresql-cnpg
    tag: 16.8
  
  name: ""
  namespace: ""

  storageSize: 2Gi
  instances: 1

  backupCluster:
    name: ""
    destinationPath: ""
    # Only for pg clusters running on clusters with Azure object storage
    azureSecret:
      secretName: ""
      name: accountName
      key: accountKey

  serviceAccount:
    annotations: {}
