global:
  registry: gsoci.azurecr.io
  provider: capa
  customer: ""

cronjob:
  image:
    name: giantswarm/kubectl
    tag: 1.31.1

  # Every day at 10:00 UTC
  schedule: "0 10 * * *"
  # 30 minutes. Time for the test to wait for the cluster's pods to be ready
  testTimeout: 1800
  # 10 minutes. Time for the test to wait for the cluster to be ready
  waitTimeout: 600

  backoffLimit: 3

  configMap:
    # Permissions for the configmap volume containing the test script and the pg cluster recovery template
    defaultMode: 0550

  serviceAccount:
    create: true
    name: pg-cluster-recovery-test

  resources: {}

  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    privileged: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  podSecurityContext:
    fsGroup: 1000
    runAsUser: 1000

pgCluster:
  image:
    name: giantswarm/postgresql-cnpg
    tag: 16.8

  name: ""
  namespace: ""

  storageSize: 2Gi
  instances: 1

  backupCluster:
    name: ""
    destinationPath: ""
    # Only for pg clusters running on clusters with Azure object storage
    azureSecret:
      secretName: ""
      name: accountName
      key: accountKey

  serviceAccount:
    annotations: {}
