# This file is a Helm values file for the pg-cluster-recovery-test chart.
#
# To learn more about how to configure your app on your cluster
# and override the default values in here, visit:
#
#   https://docs.giantswarm.io/tutorials/fleet-management/app-platform/app-configuration/#basic-values-merging-example
#
image:
  name: "giantswarm/pg-cluster-recovery-test"
  tag: ""
registry:
  domain: gsoci.azurecr.io
