global:
  registry: gsoci.azurecr.io
  provider: capa
  customer: ""

cronjob:
  image:
    name: giantswarm/kubectl
    tag: 1.31.1
    pullPolicy: IfNotPresent

  # 4 times a day: at 6:00 , 12:00, 18:00 and 00:00 UTC
  schedule: "0 */6 * * *"
  # 30 minutes. Time for the test to wait for the cluster's pods to be ready
  testTimeout: 1800
  # 30 minutes. Time for the test to wait for the cluster to be ready
  waitTimeout: 1800s

  backoffLimit: 0
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1

  configMap:
    # Permissions for the configmap volume containing the test script and the pg cluster recovery template
    defaultMode: 0550

  serviceAccount:
    create: true
    name: pg-cluster-recovery-test

  resources: {}

  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    privileged: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  podSecurityContext:
    fsGroup: 1000
    runAsUser: 1000

pgCluster:
  image:
    name: giantswarm/postgresql-cnpg
    tag: 17.5

  name: "pg-cluster-recovery-test"
  namespace: "recovey-test"

  storageSize: 2Gi
  instances: 1

  backupCluster:
    name: ""

  serviceAccount:
    annotations: {}
